os: linux
dist: xenial
language: node_js
  - 11
cache:
  - directories:
    - node_modules
install:
  - npm install
  - npm update
  - npm install -g codecov
script:
  - npm run lint
  - npm run build
  - npm run test:coverage
after_script:
  - codecov
